let FULL_ANGLE_OF_VIEW_OX_DEGREES = 30.5;
let FULL_ANGLE_OF_VIEW_OY_DEGREES = 40.6;

let SCREEN_DISTANCE_MM = 2314;
let SCREEN_WIDTH_MM = 296;
let SCREEN_HEIGHT_MM = 154;

// This is the width of the square. It's not the width of the image.
let SQUARE_IMAGE_WIDTH_PX = 200;

let DISTANCE_OF_ONE_WHEEL_REVOLUTION_MITERS = 0.97;